### ISSUE TITLE
Support Azure Network Connections

### ISSUE THREAD

**Issue by ndss8989** [terraprovider/terraform-provider-microsoft365wp#1]
Hi team
I'd love to use Azure Network Connections, to connect CloudPCs to Azure Virtual Networks.

Azure doc & API calls them "on-premises" but they're actually used for the cloud/virtualized ones
https://learn.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-1.0

The POST is like so
```
curl "https://graph.microsoft.com/beta/deviceManagement/virtualEndpoint/onPremisesConnections" ^
  -H "x-ms-client-session-id: 190d255187564dc19618fdc0f2c81a66" ^
  -H "Authorization: Bearer xxx" ^
  -H "Referer;" ^
  -H "Accept-Language: en" ^
  -H "client-request-id: e152d164-d863-4134-94ec-7a534ca64e6b" ^
  -H "x-ms-client-request-id: e152d164-d863-4134-94ec-7a534ca64e6b" ^
  -H "x-ms-command-name: createAzureConnection" ^
  -H "Accept: */*" ^
  -H "DNT: 1" ^
  -H "Content-Type: application/json" ^
  -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0" ^
  -H "x-ms-effective-locale: en.en-us" ^
  --data-raw ^"^{^\^"displayName^\^":^\^"clickops-deleteme-new-connection^\^",^\^"type^\^":^\^"azureADJoin^\^",^\^"subscriptionId^\^":^\^"0fc640d0-a8f1-4e8b-bbf5-2c225b132dbf^\^",^\^"resourceGroupId^\^":^\^"/subscriptions/0fc640d0-a8f1-4e8b-bbf5-2c225b132dbf/resourceGroups/cloudpc_admin^\^",^\^"virtualNetworkId^\^":^\^"/subscriptions/0fc640d0-a8f1-4e8b-bbf5-2c225b132dbf/resourceGroups/cloudpc_admin/providers/Microsoft.Network/virtualNetworks/vnet_cloudpc_admin^\^",^\^"subnetId^\^":^\^"/subscriptions/0fc640d0-a8f1-4e8b-bbf5-2c225b132dbf/resourceGroups/cloudpc_admin/providers/Microsoft.Network/virtualNetworks/vnet_cloudpc_admin/subnets/cloudpc_admin_private_2^\^",^\^"scopeIds^\^":^[^\^"0^\^"^]^}^" &
```

**Comment by hcoberdalhoff** [comment]
Hi, sadly the create operation for this resource currently only works with "Delegated" permissions, not "Application" permissions.

https://learn.microsoft.com/en-us/graph/api/virtualendpoint-post-onpremisesconnections?view=graph-rest-beta&tabs=http

We base our provider and testing around application permissions, as these allow automation scenarios. So, I can (currently) not help you.

It might be worthwhile to open a case / feedback-entry at Microsoft regarding application permission support :)

**Comment by hcoberdalhoff** [comment]
Created MS Graph Feedback at https://feedbackportal.microsoft.com/feedback/idea/498f7c15-9097-ef11-95f5-6045bdbc7c39

**Comment by hcoberdalhoff** [comment]
Closing, as we can currently not implement it.
